rootProject.name = 'netra_flutter'
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
//        mavenLocal()
        google()
        mavenCentral()

        maven {
            url = uri("https://maven.pkg.github.com/sinemavci/netra")
            credentials {
                username = settings.hasProperty("gpr.user") ? settings.getProperty("gpr.user") : System.getenv("GPR_USER")
                password = settings.hasProperty("gpr.key") ? settings.getProperty("gpr.key") : System.getenv("GPR_KEY")
            }
        }
    }
}